// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: test.proto

package Test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

/// 10000
type TestRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Test1 *uint32 `protobuf:"varint,1,opt,name=test1,proto3,oneof" json:"test1,omitempty"`
	Test2 *string `protobuf:"bytes,2,opt,name=test2,proto3,oneof" json:"test2,omitempty"`
}

func (x *TestRQ) Reset() {
	*x = TestRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRQ) ProtoMessage() {}

func (x *TestRQ) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRQ.ProtoReflect.Descriptor instead.
func (*TestRQ) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestRQ) GetTest1() uint32 {
	if x != nil && x.Test1 != nil {
		return *x.Test1
	}
	return 0
}

func (x *TestRQ) GetTest2() string {
	if x != nil && x.Test2 != nil {
		return *x.Test2
	}
	return ""
}

/// 10001
type TestRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Test1  *uint32  `protobuf:"varint,1,opt,name=test1,proto3,oneof" json:"test1,omitempty"`
	Test2  *string  `protobuf:"bytes,2,opt,name=test2,proto3,oneof" json:"test2,omitempty"`
	Test3S []uint64 `protobuf:"varint,3,rep,packed,name=test3s,proto3" json:"test3s,omitempty"`
}

func (x *TestRS) Reset() {
	*x = TestRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRS) ProtoMessage() {}

func (x *TestRS) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRS.ProtoReflect.Descriptor instead.
func (*TestRS) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestRS) GetTest1() uint32 {
	if x != nil && x.Test1 != nil {
		return *x.Test1
	}
	return 0
}

func (x *TestRS) GetTest2() string {
	if x != nil && x.Test2 != nil {
		return *x.Test2
	}
	return ""
}

func (x *TestRS) GetTest3S() []uint64 {
	if x != nil {
		return x.Test3S
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x06,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x51, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x31, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x32, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x74, 0x65, 0x73, 0x74, 0x31, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x32,
	0x22, 0x6a, 0x0a, 0x06, 0x54, 0x65, 0x73, 0x74, 0x52, 0x53, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x65,
	0x73, 0x74, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x05, 0x74, 0x65, 0x73,
	0x74, 0x31, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x32, 0x88, 0x01, 0x01,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x73, 0x74, 0x33, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x06, 0x74, 0x65, 0x73, 0x74, 0x33, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x31, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x32, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x3b, 0x54, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_proto_goTypes = []interface{}{
	(*TestRQ)(nil), // 0: TestRQ
	(*TestRS)(nil), // 1: TestRS
}
var file_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_test_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_test_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
